# Form implementation generated from reading ui file 'C:\Users\PC\PycharmProjects\오목봇\main_code\ui files\main_playing_game.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(parent=self.centralwidget)
        self.title.setGeometry(QtCore.QRect(0, -20, 491, 81))
        self.title.setObjectName("title")
        self.justtext1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.justtext1.setGeometry(QtCore.QRect(630, 520, 171, 21))
        self.justtext1.setObjectName("justtext1")
        self.board = QtWidgets.QLabel(parent=self.centralwidget)
        self.board.setGeometry(QtCore.QRect(180, 80, 421, 421))
        self.board.setText("")
        self.board.setPixmap(QtGui.QPixmap("/main_code/img/Board.jpg"))
        self.board.setObjectName("board")
        self.Black = QtWidgets.QLabel(parent=self.centralwidget)
        self.Black.setGeometry(QtCore.QRect(380, 280, 21, 21))
        self.Black.setText("")
        self.Black.setPixmap(QtGui.QPixmap("/main_code/img/BlackStone.png"))
        self.Black.setScaledContents(True)
        self.Black.setObjectName("Black")
        self.Black_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.Black_2.setGeometry(QtCore.QRect(407, 280, 21, 21))
        self.Black_2.setText("")
        self.Black_2.setPixmap(QtGui.QPixmap("/main_code/img/BlackStone.png"))
        self.Black_2.setScaledContents(True)
        self.Black_2.setObjectName("Black_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 33))
        self.menubar.setObjectName("menubar")
        self.menukillthemall = QtWidgets.QMenu(parent=self.menubar)
        self.menukillthemall.setObjectName("menukillthemall")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtGui.QAction(parent=MainWindow)
        self.action.setObjectName("action")
        self.menukillthemall.addAction(self.action)
        self.menubar.addAction(self.menukillthemall.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt;\">AI와의 1대1 오목 대국</span></p></body></html>"))
        self.justtext1.setText(_translate("MainWindow", "아카자여.. 오목 한판 두자꾸나.."))
        self.menukillthemall.setTitle(_translate("MainWindow", "그냥 메뉴"))
        self.action.setText(_translate("MainWindow", "바둑돌 말살"))
